### ISSUE TITLE
Documentation on how to use it

### ISSUE THREAD

**Issue by alok87** [kubernetes-incubator/custom-metrics-apiserver#10]
Need some documentation on
- where to add custom metric logic
- how to use it this custom api server
- how to deploy this api sever to the kubernetes cluster and how to aggregate it with k8s api server

**Comment by DirectXMan12** [comment]
I'd be happy to accept PRs with improvements to the documentation, or more concrete suggestions of what areas are confusing, but to answer your questions quickly for the moment:

> * where to add custom metric logic

This is described in the README under [How to use this repository](https://github.com/kubernetes-incubator/custom-metrics-apiserver#how-to-use-this-repository).  You'll have to implement the `CustomMetricsProvider` interface, and pass that implementation to the boilerplate code.  See the sample for an example of how that's done, or look at the Prometheus implementation for a real-world implementation.

> * how to use it this custom api server

I'm not entirely clear what you're asking here

> * how to deploy this api sever to the kubernetes cluster and how to aggregate it with k8s api server

That kind of process is better covered in the documentation for the aggregator, as it's common to all custom API servers.  The documentation already exists a few places, but it is a bit hard to find at the moment.  See the following for more information:

- https://github.com/DirectXMan12/k8s-prometheus-adapter/blob/master/docs/walkthrough.md
- https://github.com/kubernetes-incubator/apiserver-builder/tree/master/docs/concepts

**Comment by neilhwatson** [comment]
A start to finish example of a typical install would be very welcome.  At the moment I'm left bewildered as to how to get going with custom metrics.

**Comment by DirectXMan12** [comment]
> A start to finish example of a typical install would be very welcome. At the moment I'm left bewildered as to how to get going with custom metrics.

If you're not a developer, this repository isn't for you -- you'll want to check out one of the implementation repositories, listed here: https://github.com/kubernetes/metrics/blob/master/IMPLEMENTATIONS.md#custom-metrics-api

If you are a developer looking to get started deploying custom metrics against your own metrics solution, check out https://github.com/directxman12/k8s-prometheus-adapter as an example implementation, with a start-to-end walkthrough for deploying as well.

**Comment by diegows** [comment]
Something interesting here https://github.com/stevemcquaid/custom-metrics-apiserver/tree/dev

cc @stevemcquaid 

Maybe we can join efforts on this.

**Comment by stevemcquaid** [comment]
@diegows I'd be willing to help here. That repo is a rough effort at exactly the same goal. Bare bones example custom metrics api server.

**Comment by DirectXMan12** [comment]
If you're willing to write up a tutorial on how to develop using this library, I'd be happy to merge it.

**Comment by devdattakulkarni** [comment]
Hi,

Thanks for creating this repository.
I tried using it but ran into similar issues as mentioned earlier in this thread.

So I built an aggregated API server that supports a custom subresource using sample-apiserver as the base. Hopefully it will help anyone looking for a simple example of building an aggregated API server with custom subresources.

It is here:
https://github.com/cloud-ark/kubeprovenance

And here is our blog post explaining various approaches that we tried when building this server:

https://medium.com/@cloudark/our-journey-in-building-a-kubernetes-aggregated-api-server-29a4f9c1de22

**Comment by DirectXMan12** [comment]
@devdattakulkarni this repo is mostly intended for use with custom metrics.  It sounds like you'd like to make use of some of the custom API setup that we do, but not in the way that we use it.  You're welcome to use this as an example, but it doesn't sound like this library is the right fit for what you're trying to do.

**Comment by devdattakulkarni** [comment]
@DirectXMan12 You are right -- we are not looking to build custom-metrics api. 
This repo helped us though in understanding how things fit together. Thanks for creating it!
