### ISSUE TITLE
Should have a lightweight version of the interface

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes-incubator/custom-metrics-apiserver#2]
In some cases a more lightweight version of the provider interface may be used to implement the normal provider interface, something like this:

```go
type CustomMetricsImplementation interface {
	// ValueForMetric returns a value for a given metric for the given time frame
	ValueForMetric(name string, groupResource schema.GroupResource, namespace string, metricName string) (int64, int64)

	// ListAllMetrics provides a list of all available metrics at
	// the current time.  Note that this is not allowed to return
	// an error, so it is recomended that implementors cache and
	// periodically update this list, instead of querying every time.
	ListAllMetrics() []MetricInfo
}
```

(courtesy of https://github.com/luxas/custom-metrics-boilerplate/commit/096b8c16c45ca984ab847ab646aaf0bee48b1fcf#diff-59a31729c3bbddcc0c8999aec0c96bf3R70).

We should provide an implementation `CustomMetricsProvider` in terms of this interface, for expediency getting up and running.

**Comment by DirectXMan12** [comment]
cc @luxas

**Comment by luxas** [comment]
Yeah, this was the first simple impl I could think if, it can surely be improved significantly, but can be good as a starting point
