### ISSUE TITLE
Error from server (NotFound): the server could not find the metric http_requests for pods

### ISSUE THREAD

**Issue by D-PENG** [kubernetes-incubator/custom-metrics-apiserver#25]
Hi，How do I add `http_requests` indicators? thx.

`[root@kube-master custom-metrics-apiserver]# kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/default/pods/*/http_requests" | jq .
Error from server (NotFound): the server could not find the metric http_requests for pods
[root@kube-master custom-metrics-apiserver]# kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1" | jq .|grep http_requests
[root@kube-master custom-metrics-apiserver]# 
[root@kube-master custom-metrics-apiserver]# kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1" | jq .|grep fs_usage_bytes
      "name": "pods/fs_usage_bytes"
[root@kube-master custom-metrics-apiserver]#  `

**Comment by D-PENG** [comment]
@jsturtevant Thank you for taking time out of your busy schedule.                                                             
prometheus and podinfo runs normally.                                                                  
                                                                                                                               
> [root@kube-master ~]# kubectl get pod --all-namespaces                                                                       
> NAMESPACE     NAME                                       READY     STATUS    RESTARTS   AGE                                  
> default       podinfo-7cddffd448-4pj5g                   1/1       Running   0          6h                                   
> default       podinfo-7cddffd448-nxdv8                   1/1       Running   0          6h                                   
> kube-system   coredns-868d999555-gl5mn                   1/1       Running   1          1d                                   
> kube-system   custom-metrics-apiserver-5786465c5-ft25b   1/1       Running   0          5h                                   
> kube-system   grafana-core-64584df99d-4djvt              1/1       Running   1          1d                                   
> kube-system   metrics-server-v0.2.1-fd596d746-lzfcm      2/2       Running   0          7h                                   
> kube-system   prometheus-d676c6b74-h45xg                                                                                     
                                                                                                                               
The running parameters of custom-metrics-apiserver are                                                                         
>         args:                                                                                                                
>         - /adapter                                                                                                           
>         - --secure-port=6443                                                                                                 
>         - --tls-cert-file=/var/run/serving-cert/kubernetes.pem                                                               
>         - --tls-private-key-file=/var/run/serving-cert/kubernetes-key.pem                                                    
>         - --logtostderr=true                                                                                                 
>         - --prometheus-url=http://prometheus.kube-system.svc.cluster.local:9090/                                             
>         - --metrics-relist-interval=90s                                                                                      
>         - --rate-interval=5m                                                                                                 
>         - --v=10                                                                                                             
                                                                                                                               
                                                                                                                               
The problem now is that the `fs_usage_bytes` index is normal.                                                                  
> [root@kube-master ~]# kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/default/pods/*/fs_usage_bytes" | jq .
> {                                                                                                                            
>   "items": [                                                                                                                 
>     {                                                                                                                        
>       "value": "16384",                                                                                                      
>       "timestamp": "2018-08-16T09:22:06Z",                                                                                   
>       "metricName": "fs_usage_bytes",                                                                                        
>       "describedObject": {                                                                                                   
>         "apiVersion": "/__internal",                                                                                         
>         "name": "podinfo-7cddffd448-4pj5g",                                                                                  
>         "namespace": "default",                                                                                              
>         "kind": "Pod"                                                                                                        
>       }                                                                                                                      
>     },                                                                                                                       
>     {                                                                                                                        
>       "value": "20480",                                                                                                      
>       "timestamp": "2018-08-16T09:22:06Z",                                                                                   
>       "metricName": "fs_usage_bytes",                                                                                        
>       "describedObject": {                                                                                                   
>         "apiVersion": "/__internal",                                                                                         
>         "name": "podinfo-7cddffd448-nxdv8",                                                                                  
>         "namespace": "default",                                                                                              
>         "kind": "Pod"                                                                                                        
>       }                                                                                                                      
>     }                                                                                                                        
>   ],                                                                                                                         
>   "metadata": {                                                                                                              
>     "selfLink": "/apis/custom.metrics.k8s.io/v1beta1/namespaces/default/pods/%2A/fs_usage_bytes"                             
>   },                                                                                                                         
>   "apiVersion": "custom.metrics.k8s.io/v1beta1",                                                                             
>   "kind": "MetricValueList"                                                                                                  
> }                                                                                                                            
> [root@kube-master ~]#                                                                                                        
                                                                                                                               
The `http_requests` index does not exist，It doesn't exist in`custom.metrics.k8s.io` either.                                   
> [root@kube-master ~]# kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/default/pods/*/http_requests" | jq . 
> Error from server (NotFound): the server could not find the metric http_requests for pods                                    
> [root@kube-master ~]#

**Comment by jsturtevant** [comment]
It sounds like you are having trouble with k8s-prom-adapter.  You should open an issue on that repository: https://github.com/DirectXMan12/k8s-prometheus-adapter/issues.  This repository is for implementors that want to create their own adapters

**Comment by PrakhyaG** [comment]
@ProdanLabs I have similar issue, I am not getting both metrics output.Can you help me in the solution you used to make it work?
kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/monitoring/pods/*/fs_usage_bytes" | jq .
Error from server (NotFound): the server could not find the metric fs_usage_bytes for pods

kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/default/pods/*/http_requests" | jq .
Error from server (NotFound): the server could not find the metric http_requests for pods
