### ISSUE TITLE
Metrics Aggregator

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes-incubator/custom-metrics-apiserver#3]
In some cases, it would be nice to be able to have a single endpoint which was able to aggregate multiple different providers of the custom metrics API into a single implementation of the custom metrics API.

This could be useful if one is manually sharding metrics collection in a large cluster, or has multiple different types of metrics collection in a cluster.

**Comment by DirectXMan12** [comment]
cc @luxas @smarterclayton

**Comment by luxas** [comment]
+1 we talked about this.

Will you create an example here?

**Comment by vangarp** [comment]
From reading at other places (like https://github.com/DirectXMan12/k8s-prometheus-adapter/issues/45) seems like this is not possible at all right now. @luxas you mentioned you have an example on how one can do this?

**Comment by markusthoemmes** [comment]
@DirectXMan12 Could you line out your thoughts on how to achieve this a little more? We have this exact requirement for our Knative setup.

**Comment by DirectXMan12** [comment]
There'd be a few different ways to do this.  The custom metrics API is set up such that it's possible to use discovery to find which metrics a given server provides, and thus dispatching on that information should be fairly easy.  You'd then need a CRD representing a given source (probably a service name,namespace tuple with some metadata attached).  The CRD could be expanded to explicitly choose certain metrics if desired.

At that point, you'd have to make a decision on how to handle duplicate metric names across servers.  You could have registration allow claiming particular namespaces, or implicitly claim the namespace the service is in.

I'm curious as to what the usecase in Knative is, though.

**Comment by weikinhuang** [comment]
Hi, can we reopen this issue. I would like to use `DirectXMan12/k8s-prometheus-adapter` for pods not managed by knative, and have the knative autoscaler handle knative metrics.

Right now when you install knative serving, it installs it's own custom.metrics.k8s.io registration, making prometheus-adapter not able to be installed at the same time as it.

**Comment by SleepyBrett** [comment]
We were thinking about a proxy metrics adapter. So y9ou would wrap your metrics query in some syntax .. say `prometheus(<prometheusquery>)` and the write the metrics proxy to parse that and send it along to the proper endpoint based on the provider key.

**Comment by bradleyhession1** [comment]
Have any attempts been made to create a solution to this yet? We have a requirement for using both StackDriver + Prometheus together with HPA's

**Comment by tomkerkhove** [comment]
And KEDA (https://github.com/kedacore/keda) has customers who are using other metric providers as well.
