### ISSUE TITLE
Sample directory link in README.md is gone.

### ISSUE THREAD

**Issue by wingyplus** [kubernetes-incubator/custom-metrics-apiserver#30]
In README.md, sample directory in section [How to use this repository](https://github.com/kubernetes-incubator/custom-metrics-apiserver#how-to-use-this-repository) is pointed to https://github.com/kubernetes-incubator/custom-metrics-apiserver/blob/master/sample but this link is gone.

**Comment by DirectXMan12** [comment]
Ah, we moved the sample to `test-adapter`, but forgot to update that link.  PR is up (see #31).  Please take a look.

**Comment by wingyplus** [comment]
Thanks @DirectXMan12. Your PR is look good to me. :)
