### ISSUE TITLE
Have a question about this framework and AWS EKS clusters

### ISSUE THREAD

**Issue by shivas** [kubernetes-incubator/custom-metrics-apiserver#37]
I know AWS EKS was lacking a lot in HPA subject, and I know you guys helped them sort stuff with metrics-server, so my question is:

Is it possible to create External metrics API server with this framework and make it work on AWS EKS?

Or AWS EKS still have issues with authentication methods and webhooks/client-ca file?

**Comment by CharlyF** [comment]
@shivas the PR https://github.com/kubernetes-incubator/custom-metrics-apiserver/pull/32 should allow you to use this boilerplate to make an external metrics provider on EKS.
It basically syncs with a more recent code change the supports falling back on the requestheader CA.

**Comment by DirectXMan12** [comment]
yeah, now that #32 is merged, all the EKS issues should be unblocked.
