### ISSUE TITLE
no endpoints available for service \"custom-metrics-apiserver\"

### ISSUE THREAD

**Issue by abcdabcd987** [kubernetes-incubator/custom-metrics-apiserver#38]
Hi, I'm trying to run the `test-adapter`. I've successfully built the docker image and deployed the `testing-adapter.yaml`. But I cannot write a sample metric nor can I get the existing metrics:

```
$ kubectl get all --namespace=custom-metrics
NAME                                           READY     STATUS    RESTARTS   AGE
pod/custom-metrics-apiserver-dd9455bc9-c2vh5   1/1       Running   0          22s

NAME                               TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
service/custom-metrics-apiserver   ClusterIP   10.100.237.125   <none>        443/TCP,80/TCP   23s

NAME                                       DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/custom-metrics-apiserver   1         1         1            1           23s

NAME                                                 DESIRED   CURRENT   READY     AGE
replicaset.apps/custom-metrics-apiserver-dd9455bc9   1         1         1         23s

$ curl -XPOST http://localhost:8001/api/v1/namespaces/custom-metrics/services/custom-metrics-apiserver/proxy/write-metrics/namespaces/default/services/kubernetes/test-metric --data-raw '"300m"'

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "no endpoints available for service \"custom-metrics-apiserver\"",
  "reason": "ServiceUnavailable",
  "code": 503
}
```

It's very strange because I can see the pod is running.

I also observed that there `custom.metrics.k8s.io/v1beta1` doesn't have any resources:

```
$ curl http://localhost:8001/apis/custom.metrics.k8s.io/v1beta1
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "custom.metrics.k8s.io/v1beta1",
  "resources": []
}
```

Any clues? I'm using Kubernetes v1.12.1. Thanks!

**Comment by abcdabcd987** [comment]
OK. I figured out how to write sample metrics now, according to PR #36.

But I still cannot get the values:

```
$ curl http://localhost:8001/apis/custom.metrics.k8s.io/v1beta1
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "custom.metrics.k8s.io/v1beta1",
  "resources": [
    {
      "name": "services/test-metric",
      "singularName": "",
      "namespaced": true,
      "kind": "MetricValueList",
      "verbs": [
        "get"
      ]
    }
  ]
}

$ curl http://localhost:8001/apis/custom.metrics.k8s.io/v1beta1/services/test-metric
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "the server could not find the requested resource",
  "reason": "NotFound",
  "details": {
    
  },
  "code": 404
}
```

Also, it doesn't seem right to have `services/test-metric` as the resource name. According to [the implementation](https://github.com/kubernetes-incubator/custom-metrics-apiserver/blob/17595d72e12556524845de59f91d9ff3ca32f8ea/test-adapter/provider/provider.go#L130), it should be `services/kubernetes` and `test-metric` should be the metric name.

**Comment by DirectXMan12** [comment]
so, the "name" in discovery is in the form of "resource/sub-resource", which maps to

`/apis/custom.metrics.k8s.io/v1beta1/namespaces/<ns>/<resource>/<resource-name>/<metric-name>`

For example:

`/apis/custom.metrics.k8s.io/v1beta1/namespaces/<ns>/services/<service-name>/test-metric`

**Comment by visier-sw** [comment]
> OK. I figured out how to write sample metrics now, according to PR #36.
> 
> But I still cannot get the values:
> 
> ```
> $ curl http://localhost:8001/apis/custom.metrics.k8s.io/v1beta1
> {
>   "kind": "APIResourceList",
>   "apiVersion": "v1",
>   "groupVersion": "custom.metrics.k8s.io/v1beta1",
>   "resources": [
>     {
>       "name": "services/test-metric",
>       "singularName": "",
>       "namespaced": true,
>       "kind": "MetricValueList",
>       "verbs": [
>         "get"
>       ]
>     }
>   ]
> }
> 
> $ curl http://localhost:8001/apis/custom.metrics.k8s.io/v1beta1/services/test-metric
> {
>   "kind": "Status",
>   "apiVersion": "v1",
>   "metadata": {
>     
>   },
>   "status": "Failure",
>   "message": "the server could not find the requested resource",
>   "reason": "NotFound",
>   "details": {
>     
>   },
>   "code": 404
> }
> ```
> Also, it doesn't seem right to have `services/test-metric` as the resource name. According to [the implementation](https://github.com/kubernetes-incubator/custom-metrics-apiserver/blob/17595d72e12556524845de59f91d9ff3ca32f8ea/test-adapter/provider/provider.go#L130), it should be `services/kubernetes` and `test-metric` should be the metric name.

Hi @abcdabcd987, can you give details on how to write to a sample metric?
I used the curl command from README:

`curl -XPOST http://localhost:8080/api/v1/namespaces/custom-metrics/services/custom-metrics-apiserver:http/proxy/write-metrics/namespaces/default/services/kubernetes/test-metric --data-raw '"300m"'`

command not work and gave me an error:
`[ServiceError:400] Unable to unmarshal content of type:application/x-www-form-urlencoded`

Thanks
