### ISSUE TITLE
HPA- custom -metrics-issue

### ISSUE THREAD

**Issue by Sanjanare** [kubernetes-incubator/custom-metrics-apiserver#46]
Hi ,
I am new to k8s and have a huge confusion on creating HPA for the below query
we have a prometheus query : (sum(jvm_memory_bytes_used{area="heap"}) ) / (sum(jvm_memory_bytes_max{area="heap"}) ) 

Problem: Need to get that metrics added to prometheus adapter , so custom metrics can check those and we can implement HPA. 
and we are getting those metrics from istio-system prometheus (i dnt know if this information helps)

Kops version : 1.13.1
AWS :provider

**Comment by DirectXMan12** [comment]
if you have questions about the prometheus adapter, please file them there (https://github.com/directxman12/k8s-prometheus-adapter).
