### ISSUE TITLE
How to deploy custom-metrics-apiserver in EKS

### ISSUE THREAD

**Issue by alok87** [kubernetes-incubator/custom-metrics-apiserver#47]
Please suggest how to deploy custom metrics api server in EKS.
We are using prometheus-operator.
We are facing issue mentioned here - https://github.com/kubernetes-incubator/custom-metrics-apiserver/issues/37

We used to boot custom metrics in opensource Kubernetes using prometheus operator and its version was: `image: quay.io/coreos/k8s-prometheus-adapter-amd64:v0.2.0`  (it works)

**Comment by CharlyF** [comment]
Which version of the custom-metrics-server are you using ?
Since https://github.com/kubernetes-incubator/custom-metrics-apiserver/pull/32 was merged, it should have fixed the issue mentioned in #37.
Can you take a look at your extension-apiserver-authentication ConfigMap and confirm if you have the
`requestheader CA` available ? I believe it should still be missing the `client CA`.

If so, can you share the logs for the error so it's easier to troubleshoot ?
Best,
.C

**Comment by s-urbaniak** [comment]
@alok87 please retry with a recent version of the k8s-prometheus-adapter, there have been a lot of releases since 0.2.0: https://github.com/DirectXMan12/k8s-prometheus-adapter/releases

**Comment by alok87** [comment]
@s-urbaniak We been using custom metric api server and not k8s-prometheus-adapter. What is the difference between the two?

**Comment by alok87** [comment]
@CharlyF Can someone give me the exact steps to follow to install any of the below in EKS

- https://github.com/kubernetes-incubator/custom-metrics-apiserver
- https://github.com/DirectXMan12/k8s-prometheus-adapter

**Comment by alok87** [comment]
@s-urbaniak @CharlyF Getting this error first on installing custom metrics api server in monitoring namespace.

```
 :~/www/charts/stable/prometheus-adapter/cluster-manifests/prometheus-adapter/templates (master)*$ ls  | grep -v log | xargs -I {} kubectl --context=k8sg.practo.com create -f {} -n monitoring
clusterrolebinding.rbac.authorization.k8s.io "prometheus-adapter:system:auth-delegator" created
rolebinding.rbac.authorization.k8s.io "prometheus-adapter-auth-reader" created

error: error validating "custom-metrics-apiserver-deployment.yaml": error validating data: [ValidationError(Deployment.spec.template.spec.securityContext): unknown field "allowPrivilegeEscalation" in io.k8s.api.core.v1.PodSecurityContext, ValidationError(Deployment.spec.template.spec.securityContext): unknown field "capabilities" in io.k8s.api.core.v1.PodSecurityContext]; if you choose to ignore these errors, turn validation off with --validate=false

clusterrolebinding.rbac.authorization.k8s.io "prometheus-adapter-resource-reader" created
serviceaccount "release-name-prometheus-adapter" created
service "release-name-prometheus-adapter" created
apiservice.apiregistration.k8s.io "v1beta1.custom.metrics.k8s.io" created
clusterrole.rbac.authorization.k8s.io "prometheus-adapter-server-resources" created
configmap "release-name-prometheus-adapter" created
clusterrole.rbac.authorization.k8s.io "prometheus-adapter-resource-reader" created
clusterrolebinding.rbac.authorization.k8s.io "prometheus-adapter-hpa-controller" created
```

We are at k8s 1.11

**Comment by alok87** [comment]
Removed the security context and then deployed. It allowed to create. (assuming the security context is a thing released after k8s 1.11)
```$ kubectl create -f custom-metrics-apiserver-deployment.yaml -n monitoring
deployment.apps "release-name-prometheus-adapter" created```

**Comment by alok87** [comment]
This is the error i am getting now.
```
$ kg logs -f release-name-prometheus-adapter-9dc86d845-v97tb -n monitoring
I0404 08:47:11.765773       1 adapter.go:91] successfully using in-cluster auth
W0404 08:47:12.306167       1 authentication.go:166] cluster doesn't provide client-ca-file in configmap/extension-apiserver-authentication in kube-system, so client certificate authentication to extension api-server won't work.
F0404 08:47:12.306229       1 adapter.go:257] unable to run custom metrics adapter: unable to load client CA file: unable to load client CA file: open --v=4: no such file or directory
```
@CharlyF can you specify which flag is required to fix this.

**Comment by alok87** [comment]
Yes all worked after that change. thank you guys

**Comment by s-urbaniak** [comment]
@alok87 k8s-prometheus-adapter "implements" the custom metrics API, it literally is the custom metrics apiserver. Glad that you fixed your issue :+1:

**Comment by drewwells** [comment]
allowPrivilegeEscalation isn't in podspec for 1.11, the chart needs to be updated https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#podsecuritycontext-v1-core
