### ISSUE TITLE
Update to K8s 1.15.x libraries

### ISSUE THREAD

**Issue by mattmoor** [kubernetes-incubator/custom-metrics-apiserver#56]
There were a number of changes in 1.15.x that break callsites in this library, so consumers of this library are unable to update to 1.15.x until this library has been updated.

We currently use this as the basis for integrating our request metrics with HPA-based autoscaling in Knative, and I'd like to see us move to 1.15.x libs in our next milestone (starts tomorrow).

Any chance we can get this moved forward?

cc @markusthoemmes @vagababov @josephburnett

**Comment by CharlyF** [comment]
👋 @mattmoor - I faced the same problem. Opened this earlier today https://github.com/kubernetes-incubator/custom-metrics-apiserver/pull/55
Hopefully this (or any similar contribution) can be merged soon.

**Comment by mattmoor** [comment]
😍

**Comment by markusthoemmes** [comment]
This is done.

/close
